Adds ability to sort columns with handlebar expressions on Details List
microsoft-search/pnp-modern-search pull request #1282
Opened 2021-09-10 12:40 UTC by ellinge

Since there's a check if a column contains a handlebars expression which disallows sorting I've added the possibility to reference a sorting field when handlebars and sorting is checked.

The settings:
![bild](https://user-images.githubusercontent.com/17863113/132854628-583d4250-524e-4506-b394-857368c26db7.png)

And the result:
![bild](https://user-images.githubusercontent.com/17863113/132854659-565bafb4-26a7-47da-903a-c645741c2079.png)

2021-09-15 08:59 UTC, ellinge commented
Sonar is regarding the language files/resources as code duplication

2021-09-20 15:20 UTC, PzKfWg commented
Good job! I need exactly this :-)

2021-09-20 15:36 UTC, FranckyC requested changes

2021-09-20 15:36 UTC, FranckyC commented on search-parts/src/components/DetailsListComponent.tsx
> +              value: (column.useHandlebarsExpr && column.valueSorting) || column.value
Should be more `value: column.valueSorting ? column.valueSorting : column.value` meaning if a alternative sort field is set, the column value is always an Handlebars expression based on column possibilities (see comment below).

2021-09-20 15:36 UTC, FranckyC commented on search-parts/src/components/DetailsListComponent.tsx
> +        let allowSorting = column.enableSorting && (column.useHandlebarsExpr !== true || (column.valueSorting && column.valueSorting.length > 0));
Leaving just `column.enableSorting` should be sufficient now as we allow sort with both value/Handlebars expression now. And should be a 'const' here.

2021-09-20 15:36 UTC, FranckyC commented on search-parts/src/layouts/results/detailsList/DetailListLayout.ts
> +                    {
The 'valueSorting' column should only appear when Handlebars expression and 'sortable' options are set together. Otherwise, this column should be hidden and **empty**:

![image](https://user-images.githubusercontent.com/5659122/134027408-6d2b6105-c555-4836-a302-1cf61406e781.png)

Moreover, in the case the user revert back to a simple value, the `valueSorting` value should be reset every time.
Last thing, if the 'sortable' option is set but no value is set for 'valueSorting' then the configuration should not be saved (e.g. required field in this specific).

2021-09-20 15:36 UTC, FranckyC commented on search-parts/src/layouts/results/detailsList/DetailListLayout.ts
> +                        onCustomRender: (field, value, onUpdate, item, itemId, onCustomFieldValidation) => {
The control used here shouldn't be a `TemplateValueFieldEditor` but an `AsyncCombo`. See other examples in the code (`React.createElement(AsyncCombo, {...`

2021-09-20 19:08 UTC, ellinge commented on search-parts/src/components/DetailsListComponent.tsx
> +        let allowSorting = column.enableSorting && (column.useHandlebarsExpr !== true || (column.valueSorting && column.valueSorting.length > 0));
This will not be backwards compatible since it will try to start sorting existing webparts with enableSorting set on handlebars expressed fields since that's a possibility (but it just does not work).

2021-09-20 20:12 UTC, ellinge commented on search-parts/src/layouts/results/detailsList/DetailListLayout.ts
> +                    {
https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldCollectionData I can't find any way to update the field collection depending on the current state of all the items (any, sortable + handlebars). But setting the column label to '' sorted it out.
![image](https://user-images.githubusercontent.com/17863113/134068670-28cf71df-3617-4c5d-8e26-d621c5327cbd.png)
![image](https://user-images.githubusercontent.com/17863113/134068687-0a1e18a1-caf2-4209-8ddc-828a4fc56992.png)
Is this acceptable?

2021-09-21 06:12 UTC, ellinge commented on search-parts/src/layouts/results/detailsList/DetailListLayout.ts
> +                    {
There does not seem any other way to hide the column then setting lable to ''. This is also used for onCustomFieldValidation so I placed the requirement on enableSorting instead to be able to fulfill both these wishes.

2021-09-21 06:12 UTC, ellinge commented on search-parts/src/layouts/results/detailsList/DetailListLayout.ts
> +                        onCustomRender: (field, value, onUpdate, item, itemId, onCustomFieldValidation) => {
Changed to AsyncCombo now.

2021-09-21 06:14 UTC, ellinge commented on search-parts/src/components/DetailsListComponent.tsx
> +              value: (column.useHandlebarsExpr && column.valueSorting) || column.value
Since we added the validation for when valueSorting is possible (and cleared) there should be no need to check handleBarsExps here.

2021-09-21 06:37 UTC, ellinge commented
Finally some additional notes/findings:
- Could not find any other event which checked the current state of row / all rows to add conditional checks for header or validation while editing. onPropertyUpdate gets called after save and it then the propertyFieldCollection gets reinitialized again. I had to render custom checkboxes to do these checks. Tried getting [onGetErrorMessage ](https://github.com/pnp/sp-dev-fx-property-controls/blob/7fb3a42fcf61e69c49b7ba589dfa941b7ada62cd/src/propertyFields/collectionData/ICustomCollectionField.ts#L54)going which seems to enable conditional formatting on the current item but that did not trigger for me (it’s not triggered for custom or Boolean fields if checking code).
- https://github.com/pnp/sp-dev-fx-property-controls/blob/7fb3a42fcf61e69c49b7ba589dfa941b7ada62cd/src/loc/mystrings.d.ts does not seem to be exposed in the bundle for @pnp/spfx-property-controls so had to add typing for Required myself. Do we need to add a custom validation instead like for the label?

2021-09-22 15:33 UTC, FranckyC commented on search-parts/src/layouts/results/detailsList/DetailListLayout.ts
> +                    {
> 
> 
> https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldCollectionData I can't find any way to update the field collection depending on the current state of all the items (any, sortable + handlebars). But setting the column label to '' sorted it out.
> ![image](https://user-images.githubusercontent.com/17863113/134068670-28cf71df-3617-4c5d-8e26-d621c5327cbd.png)
> ![image](https://user-images.githubusercontent.com/17863113/134068687-0a1e18a1-caf2-4209-8ddc-828a4fc56992.png)
> Is this acceptable?

Yes that would be a solution but it only works for the initial state unfortunately, not when you configure fields dynamically. Maybe you could just let the title always empty and add a label next to the combo box, like this (juste an example):

![image](https://user-images.githubusercontent.com/5659122/134374499-a7efc112-526b-4988-b78b-11589f80c163.png)

This way we get rid of the empty column.

2021-09-22 15:34 UTC, FranckyC commented on search-parts/src/layouts/results/detailsList/DetailListLayout.ts
> +                    {
> 
> 
> There does not seem any other way to hide the column then setting lable to ''. This is also used for onCustomFieldValidation so I placed the requirement on enableSorting instead to be able to fulfill both these wishes.

I'm fine with this.

2021-09-22 15:36 UTC, FranckyC commented
> 
> 
> Finally some additional notes/findings:
> 
>     * Could not find any other event which checked the current state of row / all rows to add conditional checks for header or validation while editing. onPropertyUpdate gets called after save and then the propertyFieldCollection gets reinitialized again. I had to render custom checkboxes to do these checks. Tried getting [onGetErrorMessage ](https://github.com/pnp/sp-dev-fx-property-controls/blob/7fb3a42fcf61e69c49b7ba589dfa941b7ada62cd/src/propertyFields/collectionData/ICustomCollectionField.ts#L54)going which seems to enable conditional formatting on the current item but that did not trigger for me (it’s not triggered for custom or Boolean fields if checking code).
> 
>     * https://github.com/pnp/sp-dev-fx-property-controls/blob/7fb3a42fcf61e69c49b7ba589dfa941b7ada62cd/src/loc/mystrings.d.ts does not seem to be exposed in the bundle for @pnp/spfx-property-controls so had to add typing for Required myself. Do we need to add a custom validation message instead like for the label?

Except the column header, I'm ok with the proposed solution. If you can make the requested update regarding the label next to the combo box, we are good to go I think. Nice job!

2021-09-22 16:17 UTC, ellinge commented
Regarding the column header. The default values causes it to be visible. The label is also used as a placeholder text. Wouldn’t that suffice? 

At tops removing the conditional header.

2021-09-22 16:28 UTC, FranckyC commented
> 
> 
> Regarding the column header. The default values causes it to be visible. The label is also used as a placeholder text. Wouldn’t that suffice?
> 
> At tops removing the conditional header.

Yes basically the idea is to remove the header title to make the column "hidden" in any case. You can still use the label as placeholder text.

2021-09-22 16:40 UTC, ellinge commented
https://github.com/microsoft-search/pnp-modern-search/blob/b73293d9dbec3c1c05c4321a5ba01a962ffc8941/search-parts/src/layouts/results/detailsList/DetailListLayout.ts#L180 This placeholder should be enough then?

2021-09-22 17:19 UTC, FranckyC commented
> 
> 
> https://github.com/microsoft-search/pnp-modern-search/blob/b73293d9dbec3c1c05c4321a5ba01a962ffc8941/search-parts/src/layouts/results/detailsList/DetailListLayout.ts#L180
> This placeholder should be enough then? Both feels a bit superfluous and different compared to the other columns, if not in the header.

Just add a label next to the combo please. I've just tested and the placeholder is not visible for default values.

2021-09-24 14:54 UTC, merged

2021-09-24 14:54 UTC, FranckyC commented
Thanks @ellinge