Synonym Feature based on a SharePoint List
microsoft-search/pnp-modern-search pull request #1292
Opened 2021-09-14 09:01 UTC by Laetterman

Adds the synonym functionality to the search where the synonyms are managed in an external SharePoint list.

2021-09-14 09:13 UTC, Laetterman commented
Hi
Why does the quality check fail? I do not see what I have done wrong...

2021-09-14 17:47 UTC, wobba commented on search-parts/config/package-solution.json
> +        "version": "4.3.0.2",
We'll bump the version number :)

2021-09-14 17:47 UTC, wobba commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +                console.log("initializing/loading the synonyms table at query time...");
Please use a logging provider and not console.log

2021-09-14 17:48 UTC, wobba commented
Before we review... you more or less moved over the v3 approach right?

2021-09-14 17:57 UTC, FranckyC requested changes
Hi @Laetterman, please first fix these issues before merging.

2021-09-14 17:57 UTC, FranckyC commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +        this._synonymsService = new SynonymsService();
Please use service scopes to instanciate service instances (See other services)

2021-09-14 17:57 UTC, FranckyC commented on search-parts/src/dataSources/SharePointSearchDataSource.ts
> +     synonymsFieldNameMutual : string;
Please use a single interface to group all these properties (like ISynonymsProps)

2021-09-14 17:57 UTC, FranckyC commented on search-parts/src/dataSources/SharePointSearchDataSource.ts
> +        this._synonymsService = new SynonymsService();
Same comment as above

2021-09-14 17:57 UTC, FranckyC commented on search-parts/src/dataSources/SharePointSearchDataSource.ts
> +            if (this._synonymsList == undefined) {
Use strict equality "==="

2021-09-15 06:02 UTC, Laetterman commented on search-parts/config/package-solution.json
> +        "version": "4.3.0.2",
Absolutely fine. It was only for our internal purposes to have different versions than the main version.
Is it possible to exclude this file from the code review?

2021-09-15 06:05 UTC, Laetterman commented
Hi
Why does the quality check fail? I do not see what I have done wrong... :-)

2021-09-15 06:07 UTC, Laetterman commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +                console.log("initializing/loading the synonyms table at query time...");
This is no real logging. Just an easy way out to see when the synonym table gets loaded... :-) I'll remove the output.

2021-09-15 06:15 UTC, Laetterman commented
> Before we review... you more or less moved over the v3 approach right?

Yes. It's a new approach. One point ist that the synonyms are managed over a SharePoint list and not in the webpart itself. The main reason was that super users can manage the synonyms without having to update the webpage/page. The second reason was that (in our case) the List gets poartially updated from an external app.

The second main change is the way of lookup: in v3 the synonym entries where compared with the query. In our approach we use the oposite way: we analyze the query and use the query terms/combinations to look up for synonyms.

This we have implemented by the request of the customer and we thaugt it makes sense to make it available for others also... :-)

Regards
Marc

2021-09-15 06:17 UTC, Laetterman commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +        this._synonymsService = new SynonymsService();
Thanks for the review Franck. We will have a look at all your points you mantioned. :-)
Marc

2021-09-17 11:56 UTC, Laetterman commented on search-parts/config/package-solution.json
> +        "version": "4.3.0.2",
I have reverted it in the latest commit

2021-09-17 11:57 UTC, Laetterman commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +                console.log("initializing/loading the synonyms table at query time...");
Fixed in tle latest commit

2021-09-17 11:58 UTC, Laetterman commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +        this._synonymsService = new SynonymsService();
Fixed in the latest commits

2021-09-17 11:58 UTC, Laetterman commented on search-parts/src/dataSources/SharePointSearchDataSource.ts
> +     synonymsFieldNameMutual : string;
Fixed/Changed in the latest commit

2021-09-17 11:58 UTC, Laetterman commented on search-parts/src/dataSources/SharePointSearchDataSource.ts
> +        this._synonymsService = new SynonymsService();
Fixed in the latest commit

2021-09-17 11:59 UTC, Laetterman commented on search-parts/src/dataSources/SharePointSearchDataSource.ts
> +            if (this._synonymsList == undefined) {
Done in the latest commit

2021-09-17 14:10 UTC, dfrancoeur commented
@Laetterman Just curious about your requirement. Is the idea that the client would have a master translation table for their whole environment, stored in this list? I've seen this approach before (LiveTiles for example does this) but I worried about long term scalability, especially when the term store already has a translation feature. Do you think it would be possible to build on the general approach to lookup translations in the term store, and then append/modify the search query to look for those alternate values more dynamically?

2021-09-17 14:26 UTC, Laetterman commented
> @Laetterman Just curious about your requirement. Is the idea that the client would have a master translation table for their whole environment, stored in this list? I've seen this approach before (LiveTiles for example does this) but I worried about long term scalability, especially when the term store already has a translation feature. Do you think it would be possible to build on the general approach to lookup translations in the term store, and then append/modify the search query to look for those alternate values more dynamically?

The requirement has nothing to do with translations. Where do you get this information? It is the synonym feature introduced in v3 just with the oposite lookup aproach and management in a sharepoint list. :-)

2021-09-17 14:29 UTC, dfrancoeur commented
> > @Laetterman Just curious about your requirement. Is the idea that the client would have a master translation table for their whole environment, stored in this list? I've seen this approach before (LiveTiles for example does this) but I worried about long term scalability, especially when the term store already has a translation feature. Do you think it would be possible to build on the general approach to lookup translations in the term store, and then append/modify the search query to look for those alternate values more dynamically?
> 
> The requirement has nothing to do with translations. Where do you get this information? It is the synonym feature introduced in v3 just with the oposite lookup aproach and management in a sharepoint list. :-)

Got it. My head just went there due to my own bias. Regardless I have the same question about the Term Store and the existing Synonyms. I imagine the client just preferred the list?

2021-09-17 14:34 UTC, FranckyC commented
@Laetterman thanks for the updates
@wobba please do not merge yet. Not tested yet.

2021-09-17 14:39 UTC, Laetterman commented
> > > @Laetterman Just curious about your requirement. Is the idea that the client would have a master translation table for their whole environment, stored in this list? I've seen this approach before (LiveTiles for example does this) but I worried about long term scalability, especially when the term store already has a translation feature. Do you think it would be possible to build on the general approach to lookup translations in the term store, and then append/modify the search query to look for those alternate values more dynamically?
> > 
> > 
> > The requirement has nothing to do with translations. Where do you get this information? It is the synonym feature introduced in v3 just with the oposite lookup aproach and management in a sharepoint list. :-)
> 
> Got it. My head just went there due to my own bias. Regardless I have the same question about the Term Store and the existing Synonyms. I imagine the client just preferred the list?

We also discussed the management the synonyms in the Termstore. But we / the customer found that the Termstore management for 'simple synonym' management is not really comfortable, even in the new modern design and gaining Management access to a certain User Group is easier than to the termstore.... :-)

But I think that our integration is open/flexible so that the 'fill' of the (internal) synonyms list could also come from a termstore lookup instead of a sharepoint list...

2021-09-17 14:41 UTC, dfrancoeur commented
> > > > @Laetterman Just curious about your requirement. Is the idea that the client would have a master translation table for their whole environment, stored in this list? I've seen this approach before (LiveTiles for example does this) but I worried about long term scalability, especially when the term store already has a translation feature. Do you think it would be possible to build on the general approach to lookup translations in the term store, and then append/modify the search query to look for those alternate values more dynamically?
> > > 
> > > 
> > > The requirement has nothing to do with translations. Where do you get this information? It is the synonym feature introduced in v3 just with the oposite lookup aproach and management in a sharepoint list. :-)
> > 
> > 
> > Got it. My head just went there due to my own bias. Regardless I have the same question about the Term Store and the existing Synonyms. I imagine the client just preferred the list?
> 
> We also discussed the management the synonyms in the Termstore. But we / the customer found that the Termstore management for 'simple synonym' management is not really comfortable, even in the new modern design and gaining Management access to a certain User Group is easier than to the termstore.... :-)
> 
> But I think that our aproach is open/flexible so that the 'fill' of the (internal) synonyms list could also come from a termstore lookup instead of a sharepoint list...

I get it, thanks for confirming and appreciate the guidance. Our team will likely take a look at this.

2021-09-17 14:44 UTC, Laetterman commented
> @Laetterman thanks for the updates
> @wobba please do not merge yet. Not tested yet.

Thanks Franck and wobba. Sure, i also apreciate testing from your side and not 'blindly merge'! :-)
Greetings from Switzerland
Martc

2021-09-27 09:13 UTC, Laetterman commented
Hi @wobba 
What are the next steps? How can I resolve the 'SonarCloud Quality Gate failed' issue? I have just added new translations and do not see what I have done wrong...
Regards
Marc

2021-09-27 10:08 UTC, wobba commented
You can likely ignore sonarcloud. Still haven't had time to test this one.

2021-09-27 13:55 UTC, FranckyC commented
Hi @Laetterman, didn't have time to test. Did you update the **SynonymsService** to not use @pnp library?

2021-09-27 14:01 UTC, Laetterman commented
Hi @FranckyC 

Not sure what you really mean... :-)

Regards
Marc

> Hi @Laetterman, didn't have time to test. Did you update the **SynonymsService** to not use @pnp library?

2021-09-27 14:11 UTC, FranckyC commented
> 
> 
> Hi @FranckyC
> 
> Not sure what you really mean... :-)
> 
> We are using the whree pnp references/imports (web, list, items) to access/load the SP List which contains the Synonyms. Is there something wrong with that?
> 
> ![image](https://user-images.githubusercontent.com/38464361/134924484-8ff3a23e-f633-4039-a435-6f1eef259770.png)
> 
> Regards
> Marc
> 
> > Hi @Laetterman, didn't have time to test. Did you update the **SynonymsService** to not use @pnp library?

Yes. Services in the solution don't use the pnp library as it increases the bundle size for nothing. You can easily achieve the same thing using the `SPHttpClient` class.

2021-09-27 14:13 UTC, Laetterman commented
> > Hi @FranckyC
> > Not sure what you really mean... :-)
> > We are using the whree pnp references/imports (web, list, items) to access/load the SP List which contains the Synonyms. Is there something wrong with that?
> > ![image](https://user-images.githubusercontent.com/38464361/134924484-8ff3a23e-f633-4039-a435-6f1eef259770.png)
> > Regards
> > Marc
> > > Hi @Laetterman, didn't have time to test. Did you update the **SynonymsService** to not use @pnp library?
> 
> Yes. Services in the solution don't use the pnp library as it increases the bundle size for nothing. You can easily achieve the same thing using the `SPHttpClient` class.

@FranckyC Ahh, ok. We will have a look at it.

2021-09-27 15:57 UTC, wobba commented
One option is to have pnpjs as part of a separate bundle/chunk when you enable the synonym feature. Loading extra bytes for this feature is ok imo. I'll however let @FranckyC decide on this one.

2021-09-27 16:07 UTC, FranckyC commented
> 
> 
> One option is to have pnpjs as part of a separate bundle/chunk when you enable the synonym feature. Loading extra bytes for this feature is ok imo. I'll however let @FranckyC decide on this one.

Absolutely no value to add this library here so we stick to the `SPHttpClient`. Read items in a list shouldn't require a third party honestly...

2021-09-27 19:28 UTC, wobba commented on docs/usage/search-results/common/synonyms.md
> +Depending on a 'mutual' flag the synonyms are expanded in one direction only (keyword --> synonyms) or mutual (keywords <--> synonyms <--> synonyms).
Better to name it two-way than mutual in my opinion.

2021-09-27 19:29 UTC, wobba commented on search-parts/src/loc/da-dk.js
> +                SynonymListFieldNameMutual: "Gensidigt feltnavn (boolean)"
Boolean fields in SharePoint are name Yes/No

2021-09-27 19:33 UTC, wobba commented on search-parts/src/services/synonymsService/SynonymsService.ts
> +            const items: any[] = await web.lists.getByTitle(listName).items.get();
Some caching here would be great as reading this list upon every page load by ever user can cause unnecessary API requests. Maybe introduce a setting to set the cache interval where default is X days.

2021-09-27 19:47 UTC, wobba commented
@Laetterman These don't expand if `foo` is defined as a synonym:

`(foo)`
`(foo OR asd)`
`ANY(foo)` <- I'm ok with ANY/WORDS not expanding, as they are OR/AND inside the operator
`-foo`
`foo foo` <- turns into `(foo foo) OR (bar bar) OR (bar bar)` which might be ok, or should one permutation be "foo bar"?

2021-09-28 06:13 UTC, Laetterman commented on docs/usage/search-results/common/synonyms.md
> +Depending on a 'mutual' flag the synonyms are expanded in one direction only (keyword --> synonyms) or mutual (keywords <--> synonyms <--> synonyms).
We named it mutual by design, because if we have multiple synonyms for a keyword then 2way in our opinion means only the beack combination between the found synonym and the keyword and not amons all synonyms. :-)

2021-09-28 06:14 UTC, Laetterman commented
> > One option is to have pnpjs as part of a separate bundle/chunk when you enable the synonym feature. Loading extra bytes for this feature is ok imo. I'll however let @FranckyC decide on this one.
> 
> Absolutely no value to add this library here so we stick to the `SPHttpClient`. Read items in a list shouldn't require a third party honestly...

@wobba @FranckyC We will change it to the SPHttpClient

2021-09-28 06:31 UTC, Laetterman commented
> @Laetterman These don't expand if `foo` is defined as a synonym:
> 
> `(foo)`
> `(foo OR asd)`
> `ANY(foo)` <- I'm ok with ANY/WORDS not expanding, as they are OR/AND inside the operator
> `-foo`
> `foo foo` <- turns into `(foo foo) OR (bar bar) OR (bar bar)` which might be ok, or should one permutation be "foo bar"?

@wobba the 'ANY' operator iscurrently not stripped from the query term to get the expansion (only AND, OR and NOT as in the v3 Version). The same for the - operator. We will have a look at those special combinations...
But for the - Operateor we have to check with the customer if an exclusion should also exclude synonyms. In my opinion it should not because we are then hiding documents which the user does not understand...

For the 'optimization' of the final query: we had not the intend to re-analyze and optimize the final query as this is a compley thing and is done by the query-Analyzer in the backend. We wanted to have a syntax which is 'readable' if you have to analyze it with the dabugger. :-)  
--> Normally the end users in the UI do 98% not enter that complex queries so that the effort would be too big for a heavy optimizatuion and special cases like 'foo foo' example; the result has to be ok... :-)

2021-09-28 06:36 UTC, Laetterman commented on search-parts/src/services/synonymsService/SynonymsService.ts
> +            const items: any[] = await web.lists.getByTitle(listName).items.get();
We will have a look at it what the options are here.

Normlly the Page is loaded once and not between multiple queries. Therefore we decided to load the list at page load (as fallback on first query, eg. in debug mode). --> The list is only loaded once at page load and cached between queries
Anpother thing is, that it was a customer request to have synonyms active immediately.

2021-09-28 06:36 UTC, Laetterman commented on search-parts/src/loc/da-dk.js
> +                SynonymListFieldNameMutual: "Gensidigt feltnavn (boolean)"
I will rename it

2021-09-28 06:45 UTC, wobba commented on search-parts/src/services/synonymsService/SynonymsService.ts
> +            const items: any[] = await web.lists.getByTitle(listName).items.get();
@Laetterman Which is why a cache timeout is useful. Set to 0 for no cache, or maybe have hours/minutes as the other option.

If someone adds synonyms to a web part on an intranet home page with 100,000 employees you will have a lot of API calls not needed ;)

And, immediate synonyms is typically important for those testing, not the average person - as they have lived without the synonym up until it was added anyways 😉

2021-09-28 07:08 UTC, Laetterman commented on search-parts/src/services/synonymsService/SynonymsService.ts
> +            const items: any[] = await web.lists.getByTitle(listName).items.get();
@wobba Makes absolutely sense (was/is not an issue in our project, because the Webparts are used at a less frequently used location :-)

In terms of caching: did you meant using cookies or do you have any other mechanism in mind?

2021-09-30 13:49 UTC, wobba commented
I know what I list are edge cases which are typically not hit - but wanted to highlight them. You can address limitation in the docs as well. Can the docs state if column name should be internal name or column title names? Maybe add a comment to set the synonym table not to be indexed as well.

2021-09-30 14:01 UTC, Laetterman commented
> I know what I list are edge cases which are typically not hit - but wanted to highlight them. You can address limitation in the docs as well. Can the docs state if column name should be internal name or column title names? Maybe add a comment to set the synonym table not to be indexed as well.

Hi @wobba : absolutely fine with that. :-) I will update the docs with your hint. Especially excluding from index is a good point (as we created the list by the customers deployment script we have it already excluded over the script :-) but for manual cases you propably forget... Thanks Mikael

Info: we are currently working also on the other topics you and Franck mentioned. But as we are on heavy load at the moment it will take a little time... :-)

2021-11-03 09:09 UTC, Laetterman commented
@wobba @FranckyC 

Hi Mikael and Franck
Could you lready have a look at the changes? What are the next steps? :-)
Regards
Marc

2021-11-03 11:39 UTC, wobba commented
We will assess this one for the next release, so be patient :)

2021-11-03 12:17 UTC, Laetterman commented
> We will assess this one for the next release, so be patient :)

No worries Mikael. Just was not sure if my last checkin/update was technically correct as there are a lot of comments and changes to the dev branch meanwhile... :-)

2021-11-16 07:38 UTC, wobba commented
I've been thinking. Would it be possible to create this as a search query extension (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/building-search-extensions#associating-query-extensions-to-sites). The setup would be a bit more tricky though. 

Or a separate non-rendering web part exposed as a data source. This would allow it to be more decoupled. Connect the result webpart to the synonym part, and then the synonym part to the search box or query param etc.

Nothing definitive here and I like to have the capability in - just exploring options to decouple things.

2021-11-16 08:05 UTC, Laetterman commented
> I've been thinking. Would it be possible to create this as a search query extension (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/building-search-extensions#associating-query-extensions-to-sites). The setup would be a bit more tricky though.
> 
> Or a separate non-rendering web part exposed as a data source. This would allow it to be more decoupled. Connect the result webpart to the synonym part, and then the synonym part to the search box or query param etc.
> 
> Nothing definitive here and I like to have the capability in - just exploring options to decouple things.

Hi Mikael

Sure, we can think about it. :-)

We have built up the Feature on Customer Request (Nello from Mobiliar, I think you know him) as it is needed for their Project. We it object structally as it is for the taxonomy service or tocen service to decouple it as far as possible. Also we tried to integrate it in a way that it does not have a negative impact on the main functionality in case of failures... :-)

Unfortunately we do not have the ressources and time (and money ;-) ) to do a complete refactoring in this project and timeline... Therefore, we would appreciate if we could leave it as it is for the moment and maybe refactor it in a future version.  

Best regards
Marc

2021-11-16 17:14 UTC, wobba commented
@FranckyC what do you think... what's the effort needed to potentially remake this as a separate part to connect on the query chain, or should we just merge as is? I think I'm ok with this implementation.

2021-11-25 08:33 UTC, wobba commented
I'm changing this to draft to see if we can isolate it as an extension you can install alongside the core package and have it work. Converting to draft for now to have the code as reference.

2022-01-31 09:55 UTC, Laetterman commented
Hi @wobba @dfrancoeur 

How does it look like now? The go live date is comming closer now and we would like to use the official branch. Will this feature be merged now or do we have to manage our separate repository/branch?

I do not see where the problem is as it is a proper implementation as other services, properly documented and also a completely independent encapsulated feature...

Regards
Marc

2022-01-31 12:54 UTC, wobba commented
Hi, sorry for not following up. I still want to create this as an extension which can be dynamically added if you need it. So I'll keep the PR for code reference. For now you will have to have a custom branch.

2022-07-04 17:41 UTC, closed without merging

2022-12-05 15:00 UTC, edarroudi commented
@wobba as we have the query modifiers now I implemented this using query modifiers with minor changes and it works so far.
I'm thinking of adding it to the samples repository and creating a scenario documentation sometime in the future. 
I want to think additionally about some changes  like 

1. paging due to thresholds for query item count as this would not work with many items 
2. directly loading a JSON file.
3. Other controls / Options

I just have a problem in understanding why the whole thing is built using **"OR"** statements instead of using the **"WORDS"** statement as that actually is called a [SYNONYM operator](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#synonym-operators)

Is there a specific reason? Is this due to the fact that WORDS can not be used in property restrictions and OR can be used there?

Would be happy on any feedback on this! Thank you.

2023-07-26 15:33 UTC, LeonArmston commented
> @wobba as we have the query modifiers now I implemented this using query modifiers with minor changes and it works so far. I'm thinking of adding it to the samples repository and creating a scenario documentation sometime in the future. I want to think additionally about some changes like
> 
> 1. paging due to thresholds for query item count as this would not work with many items
> 2. directly loading a JSON file.
> 3. Other controls / Options
> 
> I just have a problem in understanding why the whole thing is built using **"OR"** statements instead of using the **"WORDS"** statement as that actually is called a [SYNONYM operator](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#synonym-operators)
> 
> Is there a specific reason? Is this due to the fact that WORDS can not be used in property restrictions and OR can be used there?
> 
> Would be happy on any feedback on this! Thank you.

Hi @edarroudi 

Looks like you made awesome progress with this in December last year. Did you ever get close to adding it to the samples gallery and writing a scenario document up?

I have a current need for synonyms in search for a client and would love to know if you or anyone cracked it in PnP Modern Search v4?

I'm unable to code anything to create a pull request but very happy to test if you have anything that can be deployed and provide feedback.

Thanks

Leon