Microsoft Search: Spelling suggestions interface
microsoft-search/pnp-modern-search pull request #1480
Opened 2021-11-04 11:15 UTC by edarroudi

I added the spelling suggestions Interface with options to set through property pane. Extended the response so it can be used in the search result webparts.

I don't know if it's mandatory to add the new labels to the different languages ( i just copied the english label to the language files for now).

2021-11-04 11:31 UTC, edarroudi commented
Should i try to get past this stupid Duplication message? Of course there is some kind of duplication for labels.

2021-12-02 09:43 UTC, edarroudi commented
Hi,

i updated the code for the develop merge and added a check for graph beta. Should i do something else here?

2021-12-03 09:56 UTC, wobba commented
Wait :)

2021-12-10 14:26 UTC, wobba commented
@FranckyC do you see any issues with merging this one?

2021-12-10 15:59 UTC, FranckyC requested changes
Please update according comments before merging Thanks!

2021-12-10 15:59 UTC, FranckyC commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +        if (this.properties.useBetaEndpoint &&
There properties should be added in the `IMicrosoftSearchRequests` through a top level interface in this case

2021-12-10 15:59 UTC, FranckyC commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +        if (this.properties.useBetaEndpoint  &&
The condition does not work as I can see these options even the "Use beta endpoint" flag is disabled.

![image](https://user-images.githubusercontent.com/5659122/145598655-fbb2333e-87c4-4bd9-8fe4-b55bb36fdaa7.png)

2021-12-10 15:59 UTC, FranckyC commented on search-parts/src/models/search/IAlteredQueryTokens.ts
> +export interface IAlteredQueryTokens {
As they are specific to Microsoft Search, these interface should be in the `IMicrosoftSearchResponse.ts` file and included in the response schema

2021-12-10 15:59 UTC, FranckyC commented on search-parts/src/models/search/IAlteredQueryTokens.ts
> +export interface IAlteredQueryTokens {
+ add links to Microsoft Search API reference

2021-12-10 15:59 UTC, FranckyC commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +import {IMicrosoftSearchDataSourceData} from "../models/search/IMicrosoftSearchDataSourceData";
Spaces here according to the other imports.

2021-12-13 04:05 UTC, FranckyC commented
Hi @edarroudi, changes have been integrated with PR #1622. Needed for December release. I'll close this one.

2021-12-13 04:05 UTC, closed without merging