Microsoft Search: KQL Extension
microsoft-search/pnp-modern-search pull request #1484
Opened 2021-11-04 14:36 UTC by edarroudi

Added a property 'Query modifier in Microsoft Search DataSource 
![image](https://user-images.githubusercontent.com/935493/140332802-cbc19d38-a8a4-4ab1-9bdb-6335b482b20c.png)

Added labels for the different languages through google translate.

It just attaches whatever is defined in the property to the queryinput text.
e.g. if template is set to 'AND IsDocument:true',  a search with the input string 'security' will be transformed to 'security AND IsDocument:true'

The template accepts tokens as done in SharePointSearch:QuerySearchTemplate.

2021-11-04 15:37 UTC, wobba commented
I think you should omit `AND` from the sample, as AND is implicit anyways in KQL.

Curious if we should add `{searchTerms}` as a concept and then replace it with the user query if present - to make it consistent from a web part point of view.

Any comments @FranckyC?

2021-11-04 15:44 UTC, edarroudi commented
> I think you should omit `AND` from the sample, as AND is implicit anyways in KQL.
> 
> Curious if we should add `{searchTerms}` as a concept and then replace it with the user query if present - to make it consistent from a web part point of view.
> 
> Any comments @FranckyC?

I did have it like this in my earlier version, but as {searchTerms} isn't part of the tokenService and i had just a regex replace for it in code it looked out of place. 

I'll remove the ADD part, forgot the implicity, thanks.

2021-11-04 15:48 UTC, edarroudi commented
found a setting error then in context if we go the way right now without {searchTerms}. allowEmptyValue has to be true.
I will fix this and the rest when you guys decicde what your want :)

2021-12-02 10:03 UTC, edarroudi commented
Hey @wobba, 
did you decide what you want: either including {searchTerms} in the modifier template or as it is right now, concat it to the inputModifier. Please tell me if i can do something else to get this approved ;-)

2021-12-02 13:19 UTC, pettersh commented
In my opinion I think the property label should be **Query template** instead of **Query modifier** for consistency. 

I understand that this feature is a query modification, but that's what SharePoint query templates does under the hood as well; modifies the user's query before it's sent to the search index.

2021-12-02 13:25 UTC, edarroudi commented
@pettersh If i rename it to Query template then i have to go the way @wobba described, include {searchTerms} in the Query template - for consitency reasons :) I think that would be better anyways for overall consistency.

2021-12-10 14:28 UTC, wobba commented
@edarroudi did you implement my ask? I think end-user familiarity is more important than the actual technical implementation. It also allows easier migration from SP API to Graph API.

2021-12-10 14:42 UTC, edarroudi commented
@wobba  sorry - didn'T see your thumbs up. I'll do it till monday.

2021-12-10 16:18 UTC, FranckyC requested changes
Please update according to comments before merging. Also check with the current `develop` branch and add missing translations if any. Thanks!

2021-12-10 16:18 UTC, FranckyC commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +            queryText = `${queryText} ${queryModifierTemplate.trimLeft()}`;
Wrong statement, you should have the same behavior as the SharePoint search. The query text should be included on demand using either `{searchTerms}` and `{inputQueryText}` tokens. It means you should add `{searchTerms}` as a builtin token and resolve it the same way as `{inputQueryText}`.

2021-12-10 16:18 UTC, FranckyC commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +    queryModifierTemplate: string;
Rename to `queryTemplate` to align with SharePoint Search

2021-12-10 16:18 UTC, FranckyC commented on search-parts/src/dataSources/MicrosoftSearchDataSource.ts
> +        this.properties.queryModifierTemplate = this.properties.queryModifierTemplate ?? "";
Use the same initialization as SharePoint Search `this.properties.queryTemplate = this.properties.queryTemplate ? this.properties.queryTemplate : "{searchTerms}";`

2021-12-13 02:54 UTC, FranckyC commented
Hi @edarroudi, I've made the changes in the PR #1621 because I needed them before the December release. I'll close this one.

2021-12-13 02:54 UTC, closed without merging