Added support for actionable Adaptive Cards in results
microsoft-search/pnp-modern-search pull request #2243
Opened 2022-07-20 16:35 UTC by PaoloPia

This PR introduces the following changes:

- Updated behavior of Adaptive Cards rendering accordingly to what we have in the AdaptiveCardHost control in PnP React Controls (Fluent UI, themes, and serialization context)
- Support for actionable Adaptive Cards (we can now define Adaptive Cards with actions that trigger code in registered instances of IExtensibilityLibrary)
- Updated rendering model for results (TemplateRenderer.tsx) using React.RefObject<HTMLDivElement> instead of dangerouslySetInnerHTML
- Added optional support for ServiceScope in instances of IExtensibilityLibrary (so that we can access SPFx context and services from within instances of IExtensibilityLibrary)
- Updated docs accordingly to the above changes

2022-07-25 17:53 UTC, FranckyC commented
Hi @PaoloPia, thanks for the PR! I'll look at this as soon as I get some time :D

2022-07-28 20:10 UTC, FranckyC requested changes
@PaoloPia I've made a first review with my comments. Works well overall, nice job ;) If you can address the points I mentionned, we could merge this for the next release. Thanks!

2022-07-28 20:10 UTC, FranckyC commented on search-parts/src/controls/TemplateRenderer/TemplateRenderer.tsx
> +                GlobalRegistry.populateWithDefaultElements(elementRegistry);
The issue I see here is the `invokeCardAction` method will be triggered for all Web Part instances on the same page using adaptive cards and actions, regardless if the Web Part loads the extensibility library explicitly (it only requires one Web Part to load the library for all other ones). It may leads to some errors and undesired behaviors. However, because we use action properties like "title" to determine the code to execute, we need to find a way to either isolate the actions per Web Parts instances or, worst case, mention in the documentation this limitation and tell developers to use unique identifiers for actions in their templates.

2022-09-08 14:36 UTC, FranckyC commented
@PaoloPia could you process with requested changes so I could add it to next release? Thanks!

2022-09-10 10:46 UTC, PaoloPia commented on search-parts/src/controls/TemplateRenderer/TemplateRenderer.tsx
> +import { Action, CardElement, CardObjectRegistry, GlobalRegistry, SerializationContext } from 'adaptivecards';
Done, updated branch is coming ...

2022-09-10 10:46 UTC, PaoloPia commented on search-parts/src/services/templateService/TemplateService.ts
> +import { Action, ExecuteAction, OpenUrlAction, SubmitAction } from 'adaptivecards';
Done, updated branch is coming ...

2022-09-10 10:47 UTC, PaoloPia commented on search-parts/src/controls/TemplateRenderer/fluentUI/Actions.tsx
> +import { ActionButtonState, ActionIconPlacement, defaultHostConfig, ExecuteAction, OpenUrlAction, ShowCardAction, SubmitAction, ToggleVisibilityAction } from "adaptivecards";
Can we start as it is and then consolidate it later together with Fabio Franzini, who is the one taking care of the AdaptiveCardHost control?

2022-09-10 11:13 UTC, PaoloPia commented on docs/extensibility/adaptivecards_customizations.md
> +# Register Adaptive Cards Actions handlers customizations
Sure I will create a sample and share it. I think it is better to do that as soon as the functionality will be released so that I can reference the right version of the package.

2022-09-10 11:28 UTC, PaoloPia commented on search-parts/src/controls/TemplateRenderer/TemplateRenderer.tsx
> +                GlobalRegistry.populateWithDefaultElements(elementRegistry);
Here I need further testing. Have you tested the scenario that you are describing or are you just making assumptions? As far as I know, the _populateWithDefaultActions_ method registers default actions only. Then in custom code, I register the extensibility function for every specific adaptive card (TemplateService.ts:462). Then, for sure in a single web part instance, all the actions trigger the same method and developers will have to determine the code to execute based on the title property of the action, I think we can only document it. Most likely I am missing something because I'm not deep in the internal architecture of PnP Modern Search as you are. Please, help me understand your concern. Thanks.

2022-09-10 11:53 UTC, PaoloPia commented on search-parts/src/controls/TemplateRenderer/TemplateRenderer.tsx
> +                useLocalFluentUI(elementRegistry, actionRegistry);
You're totally right. I'm investigating the issue. It should work differently :-) ...

2022-09-10 14:46 UTC, PaoloPia commented on search-parts/src/controls/TemplateRenderer/fluentUI/Actions.tsx
> +import { ActionButtonState, ActionIconPlacement, defaultHostConfig, ExecuteAction, OpenUrlAction, ShowCardAction, SubmitAction, ToggleVisibilityAction } from "adaptivecards";
Meanwhile, I'll have a meeting with Fabio next Monday to discuss the options.

2022-09-12 11:04 UTC, PaoloPia commented on search-parts/src/controls/TemplateRenderer/TemplateRenderer.tsx
> +                useLocalFluentUI(elementRegistry, actionRegistry);
It is now fixed and merged in my local branch, related to this PR.

2022-09-12 11:09 UTC, PaoloPia commented on search-parts/src/controls/TemplateRenderer/fluentUI/Actions.tsx
> +import { ActionButtonState, ActionIconPlacement, defaultHostConfig, ExecuteAction, OpenUrlAction, ShowCardAction, SubmitAction, ToggleVisibilityAction } from "adaptivecards";
Ok, we (me and Fabio) have made a plan. We would like to create a dedicated npm package for the FluentUI extensions for Adaptive Cards. It should go under the @pnp family of packages. We should be able to release it around early October. So, now we have two options: 1) we can ship what we have and update it later; 2) we can wait until mid-October for this release. What's your preference?

2022-09-12 11:11 UTC, PaoloPia commented
Hey @FranckyC, I'm done with my duties except for one, where I need clarification. Please let me know and I will be happy to complete my tasks. Thanks.

2022-09-12 18:36 UTC, FranckyC commented on search-parts/src/controls/TemplateRenderer/fluentUI/Actions.tsx
> +import { ActionButtonState, ActionIconPlacement, defaultHostConfig, ExecuteAction, OpenUrlAction, ShowCardAction, SubmitAction, ToggleVisibilityAction } from "adaptivecards";
If the PR is all functional, then we can release right now and make the fix as soon as the npm package is available.

2022-09-12 18:38 UTC, FranckyC commented on search-parts/src/controls/TemplateRenderer/TemplateRenderer.tsx
> +                GlobalRegistry.populateWithDefaultElements(elementRegistry);
I've tested this scenario and experienced this behavior. Not a big thing, I agree we can mitigate this with good documentation.

2022-09-12 19:22 UTC, FranckyC approved these changes

2022-09-12 19:22 UTC, merged

2022-09-12 19:23 UTC, FranckyC commented
Let release this first version so people can test. We will improve it along the way. Thanks for this contribution @PaoloPia!

2022-09-13 15:44 UTC, FranckyC commented on docs/extensibility/adaptivecards_customizations.md
> +# Register Adaptive Cards Actions handlers customizations
@PaoloPia I've added the action sample to the extensibility samples repository https://github.com/microsoft-search/pnp-modern-search-extensibility-samples/blob/main/search-extensibility-samples/src/libraries/myCompanyLibrary/MyCompanyLibraryLibrary.ts and published the extensibility npm package `1.4.0` version. Nothing to do on your side :)